### ISSUE TITLE
OpenAPI file finalization 

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/bpdm-certificate-management#11]
Creating a first final version of the open API file with the data model of business partner certificates.

Based on the following data model:
https://github.com/eclipse-tractusx/sldt-semantic-models/issues/415

**Comment by SujitMBRDI** [comment]
##Description:

Creation of the first final version of the OpenAPI file that captures the data model for business partner certificate management.

## OpenAPI File Requirements:

Scope: The OpenAPI file should encompass the data model for business partner certificates.
Specification Version: OpenAPI 3.0.x
Format: yaml file
Data Model:
A high-level overview of the data model for business partner certificates. Include key entities, attributes, and relationships.
Validation: Ensure the OpenAPI file includes appropriate validation for data consistency and integrity.
Documentation: Include clear and comprehensive documentation for each endpoint, parameter, and response.
Integration and Usage:
Intended Usage: OpenApi model for code generation in the project.
