### ISSUE TITLE
Create semantic model based on SAMM for the company certificate data model

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/bpdm-certificate-management#12]
The following data model needs to be transferred into a SAMM based semantic model:

[Catena-X Semantic Model Certificates.xlsx](https://github.com/eclipse-tractusx/bpdm-certificate-management/files/13349266/Catena-X.Semantic.Model.Certificates.xlsx)

**Comment by SujitMBRDI** [comment]
Hello @maximilianong and @chr-krenn,

I have update data model which need to be transfer into a SAMM based semantic model:

[Catena-X Semantic Model Certificates_20230913_V1.xlsx](https://github.com/eclipse-tractusx/bpdm-certificate-management/files/13786546/Catena-X.Semantic.Model.Certificates_20230913_V1.xlsx)
Here, i have updated attribute names, datatype to meaning full names and in initial development phase i have follow the same approch.
I didn't made any changes on examples provided but there are changes you can observe inside sheet of API design and API design Mgmt API. Where i have changed some response code and messages.

**Comment by SujitMBRDI** [comment]
Reference on pull request:
[https://github.com/eclipse-tractusx/sldt-semantic-models/pull/673](https://github.com/eclipse-tractusx/sldt-semantic-models/pull/673)

**Comment by SujitMBRDI** [comment]
Reference pull request from sldt-semantic-models - [https://github.com/eclipse-tractusx/sldt-semantic-models/pull/673](https://github.com/eclipse-tractusx/sldt-semantic-models/pull/673)
