### ISSUE TITLE
API: Simplified API to check if legal entity/site/address has requested certificate

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/bpdm-certificate-management#3]
As a user a company provided me a certificate and I want to validate this, so that I can trust this certificate or not. Additionally I get the trust level and the data til the certificate is valid.

Trust levels:

- None: no validation check at all, just uploaded / provided
- low: manual validation check done by human after upload
- medium: certificate provided by trusted issuer and manually checked (as low)
- high: automated cross check via some database (e.g. TÜV, IATF)
- trusted: directly provided by issuer (e.g. TÜV)

API-Call (get): [https://cert-system.net/api/catena/certificate/simple/](https://cert-system.net/api/catena/certificate/simple/){bpn}/{certificateType}

Returns true/false and certification valid-until, trust level

- [x]  Response body: true / false, certification valid-until and the trust level
- [x]  Make BPN L/S/A as mandatory
- [x]  Make certificateType as mandatory

**Comment by maximilianong** [comment]
@ Christian - the question came up - why do we need this when the other endpoint provides much more value. 

My thought is that we need this endpoint so that service providers don't have to provide all information about a business partner and their certificate information every time. Instead, they can simply return true/false as basic information. Can you confirm this reason or are there any others?

**Comment by nicoprow** [comment]
> @ Christian - the question came up - why do we need this when the other endpoint provides much more value.
> 
> My thought is that we need this endpoint so that service providers don't have to provide all information about a business partner and their certificate information every time. Instead, they can simply return true/false as basic information. Can you confirm this reason or are there any others?

@maximilianong Considering that each certificate has also its document attached which in theory can be quite big in itself, it makes sense to divide views on the certificate. I would, however, propose to just keep all certificate information together and just split the actual certificate document file apart into another endpoint. So far the certificate information is quite small anyway. The only big part is the actual document file. If you separate it like that you can basically just go with one representation of the certificate information which simplifies things.

**Comment by nicoprow** [comment]
> As a user a company provided me a certificate and I want to validate this, so that I can trust this certificate or not. Additionally I get the trust level and the data til the certificate is valid.
> 
> Trust levels:
> 
>     * None: no validation check at all, just uploaded / provided
> 
>     * low: manual validation check done by human after upload
> 
>     * medium: certificate provided by trusted issuer and manually checked (as low)
> 
>     * high: automated cross check via some database (e.g. TÜV, IATF)
> 
>     * trusted: directly provided by issuer (e.g. TÜV)
> 
> 
> API-Call (get): https://cert-system.net/api/catena/certificate/simple/{bpn}/{certificateType}
> 
> Returns true/false and certification valid-until, trust level
> 
>     * [ ]   Response body: true / false, certification valid-until and the trust level
> 
>     * [ ]   Make BPN L/S/A as mandatory
> 
>     * [ ]   Make certificateType as mandatory

@maximilianong I got a question regarding the true/false for wether a certificate is trusted. If you have trust levels it gives an information to the user how much he can trust this certificate already. What is the true/false supposed to mean? Is it true from the certain trust level onwards or where is this true/false being calculated?

**Comment by SujitMBRDI** [comment]
> > As a user a company provided me a certificate and I want to validate this, so that I can trust this certificate or not. Additionally I get the trust level and the data til the certificate is valid.
> > Trust levels:
> > ```
> > * None: no validation check at all, just uploaded / provided
> > 
> > * low: manual validation check done by human after upload
> > 
> > * medium: certificate provided by trusted issuer and manually checked (as low)
> > 
> > * high: automated cross check via some database (e.g. TÜV, IATF)
> > 
> > * trusted: directly provided by issuer (e.g. TÜV)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > API-Call (get): [https://cert-system.net/api/catena/certificate/simple/{bpn}/{certificateType}](https://cert-system.net/api/catena/certificate/simple/%7Bbpn%7D/%7BcertificateType%7D)
> > Returns true/false and certification valid-until, trust level
> > ```
> > * [ ]   Response body: true / false, certification valid-until and the trust level
> > 
> > * [ ]   Make BPN L/S/A as mandatory
> > 
> > * [ ]   Make certificateType as mandatory
> > ```
> 
> @maximilianong I got a question regarding the true/false for wether a certificate is trusted. If you have trust levels it gives an information to the user how much he can trust this certificate already. What is the true/false supposed to mean? Is it true from the certain trust level onwards or where is this true/false being calculated?

Hi @nicoprow as per my understanding and discussion for demand on use case, IsCertified attribute should be derived true/false based on provided bpn and certificateType exists in a system. If yes then it will be return true along with details of the certification like validUntil, trustLevel. And if no then it will return false without certification details.

**Comment by maximilianong** [comment]
> > As a user a company provided me a certificate and I want to validate this, so that I can trust this certificate or not. Additionally I get the trust level and the data til the certificate is valid.
> > Trust levels:
> > ```
> > * None: no validation check at all, just uploaded / provided
> > 
> > * low: manual validation check done by human after upload
> > 
> > * medium: certificate provided by trusted issuer and manually checked (as low)
> > 
> > * high: automated cross check via some database (e.g. TÜV, IATF)
> > 
> > * trusted: directly provided by issuer (e.g. TÜV)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > API-Call (get): [https://cert-system.net/api/catena/certificate/simple/{bpn}/{certificateType}](https://cert-system.net/api/catena/certificate/simple/%7Bbpn%7D/%7BcertificateType%7D)
> > Returns true/false and certification valid-until, trust level
> > ```
> > * [ ]   Response body: true / false, certification valid-until and the trust level
> > 
> > * [ ]   Make BPN L/S/A as mandatory
> > 
> > * [ ]   Make certificateType as mandatory
> > ```
> 
> @maximilianong I got a question regarding the true/false for wether a certificate is trusted. If you have trust levels it gives an information to the user how much he can trust this certificate already. What is the true/false supposed to mean? Is it true from the certain trust level onwards or where is this true/false being calculated?

True / false is just for: in general the company has a certificate. However the trust level ist. That means the lowest trust level gives you a "true".

**Comment by maximilianong** [comment]
> > @ Christian - the question came up - why do we need this when the other endpoint provides much more value.
> > My thought is that we need this endpoint so that service providers don't have to provide all information about a business partner and their certificate information every time. Instead, they can simply return true/false as basic information. Can you confirm this reason or are there any others?
> 
> @maximilianong Considering that each certificate has also its document attached which in theory can be quite big in itself, it makes sense to divide views on the certificate. I would, however, propose to just keep all certificate information together and just split the actual certificate document file apart into another endpoint. So far the certificate information is quite small anyway. The only big part is the actual document file. If you separate it like that you can basically just go with one representation of the certificate information which simplifies things.

But I thought this is now solved with the encoding of the document?!

**Comment by nicoprow** [comment]
> > > @ Christian - the question came up - why do we need this when the other endpoint provides much more value.
> > > My thought is that we need this endpoint so that service providers don't have to provide all information about a business partner and their certificate information every time. Instead, they can simply return true/false as basic information. Can you confirm this reason or are there any others?
> > 
> > 
> > @maximilianong Considering that each certificate has also its document attached which in theory can be quite big in itself, it makes sense to divide views on the certificate. I would, however, propose to just keep all certificate information together and just split the actual certificate document file apart into another endpoint. So far the certificate information is quite small anyway. The only big part is the actual document file. If you separate it like that you can basically just go with one representation of the certificate information which simplifies things.
> 
> But I thought this is now solved with the encoding of the document?!

Ah, I just checked the certficate response and yea the document file is already not in that response. So it won't be returned with the other certificate information. In that case I think even more that such a separate endpoint is not needed. Users could just use the normal GET certificate by BPN and type endpoint. 

Anyway, I guess that's up to preference

**Comment by SujitMBRDI** [comment]
> > > > @ Christian - the question came up - why do we need this when the other endpoint provides much more value.
> > > > My thought is that we need this endpoint so that service providers don't have to provide all information about a business partner and their certificate information every time. Instead, they can simply return true/false as basic information. Can you confirm this reason or are there any others?
> > > 
> > > 
> > > @maximilianong Considering that each certificate has also its document attached which in theory can be quite big in itself, it makes sense to divide views on the certificate. I would, however, propose to just keep all certificate information together and just split the actual certificate document file apart into another endpoint. So far the certificate information is quite small anyway. The only big part is the actual document file. If you separate it like that you can basically just go with one representation of the certificate information which simplifies things.
> > 
> > 
> > But I thought this is now solved with the encoding of the document?!
> 
> Ah, I just checked the certficate response and yea the document file is already not in that response. So it won't be returned with the other certificate information. In that case I think even more that such a separate endpoint is not needed. Users could just use the normal GET certificate by BPN and type endpoint.
> 
> Anyway, I guess that's up to preference

Yeah, with same feeling i asked actual need of this endpoint but i think answer is still pending

**Comment by maximilianong** [comment]
Just for my information - this is the discussion we had today in our weekly, right @SujitMBRDI ?

**Comment by SujitMBRDI** [comment]
> Just for my information - this is the discussion we had today in our weekly, right @SujitMBRDI ?

@maximilianong, yes we were talking about this endpoint.
