### ISSUE TITLE
KIT - create adoption view content

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/bpdm-certificate-management#41]
Each KIT has an adoption view that needs to contain the following content:

- [x] Logo / Icon

- [x] Vision & Mission
- [x] Business Value
- [x] Use Case / Domain explanation
- [x] Business Process
- [x] Standards
- [x] Notice

**Comment by maximilianong** [comment]
Logo + Icon :

![Certificate_KIT_Icon](https://github.com/eclipse-tractusx/bpdm-certificate-management/assets/83761111/3ab573cb-c52a-4468-9898-623bb0ed3327)
![Certificate_KIT](https://github.com/eclipse-tractusx/bpdm-certificate-management/assets/83761111/f11dd424-d6d1-469e-8d1a-5fc26bd6f993)

**Comment by SujitMBRDI** [comment]
Reference of pull request from KITs- [https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/684](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/684)
