### ISSUE TITLE
KIT - operation view

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/bpdm-certificate-management#42]
The operation view of the KIT provides resources to deploy and operate centralized & decentralized Catena-X offerings in your IT environment (e.g., on-prem, cloud).

Deliverables: Quick Setup Guide / Installation Instructions

Prerequisites (if they exist)
Authorization information
Deployment Deployment Scripts

**Comment by SujitMBRDI** [comment]
Reference of pull request from KITs- [https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/684](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/684)
