### ISSUE TITLE
Master Admin functionality

### ISSUE THREAD

**Issue by alexKeppler** [eclipse-tractusx/bpdm-certificate-management#51]
Currently onboarding happens on a BPNL level. As there is no information available which BPNL is a subsidiary of another BPNL, both BPNLs have to be registered seperately which leads to a high maintenance effort.

Once a hierarchie concept from the CX association is designed and implemented, we want to have the functionality to select one master admin for multiple BPNLs. This allows the user to maintain all certificate information for all its assigned BPNLs.

**Comment by SujitMBRDI** [comment]
Closing issue to enable archiving of repository `bpdm-certificate-management`.
