### ISSUE TITLE
Life cycle management

### ISSUE THREAD

**Issue by alexKeppler** [eclipse-tractusx/bpdm-certificate-management#52]
Life cycle management is the functionality to receive notifications prior to a certificate expiration. 

During upload of a certificate the validity information has to be provided. Given that information, the application needs to send notifications 1 month prior to the certificate expiration and on the day of the expiration. The exact time to the notifications needs to be customized by the application provider.

**Comment by alexKeppler** [comment]
Additional requirement: Notification via mail

**Comment by jjeroch** [comment]
Work in progress - rechecking the details by today eod

**Comment by SujitMBRDI** [comment]
Closing issue to enable archiving of repository `bpdm-certificate-management`.
