### ISSUE TITLE
API: MetadataController / Management API

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/bpdm-certificate-management#6]
As a developer that implements the business partner certificate API I want to get a list of registered certificate types so that I know how the spelling is and what certificate types are available - that's needed for the usage of other API endpoints in this use case.

As a developer that implements the business partner certificate API I want to register a new certificate type, so that I can provide new certificates where the type is not known so far. That's needed for the post API of this use case.

API-Call (get): MetaDataController/api/catena/certificate-types - returns all currently registered certificate types
API-Call (post): MetaDataController/api/catena/create-certificate-type - register certificate type

**Comment by maximilianong** [comment]
How to we make sure that an existing certificate type will be registered twice with a different spelling?

**Comment by maximilianong** [comment]
@chr-krenn

Question related to:
**Certificate-types**
contains the type and the version
one type can have several versions, correct?

**Comment by chr-krenn** [comment]
> @chr-krenn
> 
> Question related to: **Certificate-types** contains the type and the version one type can have several versions, correct?

Yes, but not dynamically. e.g. IATF16949-2015 -> 2015 is the version. If the authorities define a new version of IATF it could be e.g. IATF16949-2024 but a certificate document is then either the one or the otheer type-version combination, never both. So version is just a refinement description of a certificate type.

**Comment by maximilianong** [comment]
> > @chr-krenn
> > Question related to: **Certificate-types** contains the type and the version one type can have several versions, correct?
> 
> Not dynamically. e.g. IATF16949-2015 -> 2015 is the version. If the authorities define a new version of IATF it could be e.g. IATF16949-2024 but a certificate document is then either the one or the other type-version combination, never both. So version is just a refinement description of a certificate type. For managing certificates, usually only the type is required, not the specific version.

The IATF overall certificate version will not change that often right?

But I mean - today I got a IATF certificate as Company A and this is valid for one year. After that one year I get a new IATF certificate. Based on the same overall certification, so should we document this in the same dataset?

**Comment by maximilianong** [comment]
> How to we make sure that an existing certificate type will be registered twice with a different spelling?

@chr-krenn do you have an opinion to that?
