### ISSUE TITLE
Adoption of TISAX to the data model and API 

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/bpdm-certificate-management#66]
### Description
As a user I want to be able to request and provide TISAX certificates via the certificate management API and data model.

Pre-condition:
We want to stay with our generic approach as much as possible and do not want to build a custom solution for TISAX.

TISAX is a bit different to an ISO or IATF certificate. In this ticket we document our open questions and points.

### Open points to discuss:

1.
TISAX contains assessment objectives and label per location
To align this to our data model it would look like this:
CertificateType: TISAX
CertificateRequestNumber: AssessmentID
Enclosed Sites: BPN S / A + AreaOfApplication: TISAX label

and do not enable another attribute for TISAX labels

**Comment by maximilianong** [comment]
FYI @SujitMBRDI + @chkrenn

**Comment by SujitMBRDI** [comment]
Closing issue to enable archiving of repository `bpdm-certificate-management`.
