### ISSUE TITLE
New attribute [status] to data model and API 

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/bpdm-certificate-management#74]
Please add one attribute to the data model and availability via API.
With three possible values: active, inactive, pending 

Attribute: status

This is optional and can be set by the system.

**Comment by alexKeppler** [comment]
Hi Sujit,

1. Active should be (validUntil date >= current date). Inactive is correct. Pending could also be if the certificate is uploaded today but only valid from next month on. So in the meantime it is pending. Maybe there is a better word for it. There needs to be some kind of batch job which checks the status pending once every day or so and change the status accordingly if the certificate is now active (validUntil date >= current date).
2. For me it is not connected to the TrustLevel at the moment. 

In general this attribute shall give us the possibility of filtering results and provides an easier overview. E.g. if I request all ISO9001 certificates from one partner and the result is 5, I do not know which is the active one without the status information. Then I have to open each certificate which is just not easy to use.
