### ISSUE TITLE
Setting up ArgoCD

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/bpdm-certificate-management#9]
Name space + permissions @ArgoCD 
Request needs to be addressed to the DevSecOps team

**Comment by maximilianong** [comment]
@SujitMBRDI please add information to this issue if I missed a topic.

**Comment by SujitMBRDI** [comment]
## Description:

Tittle: ArgoCD Environment Creation - bpdm-certificate-management

Request to DevSecOps team to set up ArgoCD environments for the "bpdm-certificate-management" project. This includes creating environments for both development (Dev) and integration (Int) where we can use Helm charts.

## Project Details:
Project Name: bpdm-certificate-management 
Environments: Development (Dev),Integration (Int)
Helm Charts: Any specific Helm charts to be used, or indicate if the default ArgoCD Helm charts are acceptable.
Secrets/Keys Handling: vault secrets
Include any additional details or special considerations relevant to the ArgoCD environment setup.
